git:
  depth: 1
dist: xenial
language: python
cache:
  pip: true
matrix:
  include:
  - python: "3.5"
    env: |
      SPHINX_VERSION='==1.5'
  - python: "3.7"
    env: |
      SPHINX_VERSION=
install: |
  pip install --upgrade pip pytest"$PYTEST_VERSION" pytest-cov codecov
  pip install --upgrade sphinx"$SPHINX_VERSION"
  pip install .
  pip list
script: pytest --cov
after_success: codecov
