name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            python-version: "3.6"
          - os: ubuntu-latest
            python-version: "3.12"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -mpip install --upgrade pip setuptools wheel pytest
        case '${{ matrix.python-version }}' in
        3.6)
          pip install sphinx==1.7;;
        esac
        python -mpip install .
    - name: Test
      run: |
        python -mpytest  # No coverage checks, as everything happens in a subprocess.
