name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.5", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -mpip install --upgrade pip setuptools wheel pytest pytest-cov
        case '${{ matrix.python-version }}' in
        3.5)
          pip install sphinx==1.7;;
        3.10)
          ;;
        *)
          exit 1;;
        esac
        python -mpip install .
    - name: Test
      run: |
        python -mpytest --cov --cov-branch
        python -mcoverage report --show-missing
